- name : Deply sudo configuration
  hosts: all
  become: true
  become_user: root
  tasks:
    - name: Change sudo configuration using lineinfile
      lineinfile:
        path: /etc/sudoers
        regexp: 'sshuser ALL='
        line: 'sshuser ALL=(ALL) NOPASSWD: ALL'
        state: present
    

- name : Install apache & php
  hosts: web
  tasks:
    - name: install apache
      apt: name=apache2
      notify: lancer Apache

    - name: install php
      apt: name=php
      notify: lancer php


  handlers:
    - name: lancer Apache
      service: name=apache2 state=started
    